[meta]
name        = "Catppuccin Latte"
author      = "catppuccin"
dark        = false
description = "Catppuccin is a community-driven pastel theme that aims to be the middle ground between low and high-contrast themes."
source      = "https://github.com/catppuccin/catppuccin"
