Gtk/ThemeName "adw-gtk3-dark"
Gtk/IconThemeName "Tela-circle-dracula"
Gtk/FontName "JetBrainsMono Nerd Font 12"
Gtk/CursorThemeName "Bibata-Modern-Classic"
Gtk/CursorThemeSize 20
Gtk/ButtonImages 1
Gtk/MenuImages 1
Gtk/EnableEventSounds 1
Gtk/EnableInputFeedbackSounds 1
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"